[project]
name = "fastapi-async-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi[standard]>=0.124.4",
    "psutil>=7.1.3",
    "wordfreq>=3.1.1",
]
